// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WSInformatica.Models;

#nullable disable

namespace WSInformatica.Migrations
{
    [DbContext(typeof(InfoContext))]
    [Migration("20250625143547_HacerMovilNulleable")]
    partial class HacerMovilNulleable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WSInformatica.Models.Arma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Calibre")
                        .HasColumnType("int");

                    b.Property<int?>("ConsultaId")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumArma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Resultado")
                        .HasColumnType("bit");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaId");

                    b.ToTable("Arma");
                });

            modelBuilder.Entity("WSInformatica.Models.Automotor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Chasis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConsultaId")
                        .HasColumnType("int");

                    b.Property<string>("Dominio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Resultado")
                        .HasColumnType("bit");

                    b.Property<int?>("TipoAutomotorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaId");

                    b.ToTable("Automotor");
                });

            modelBuilder.Entity("WSInformatica.Models.Consulta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdDespachante")
                        .HasColumnType("int");

                    b.Property<int>("IdSolicitante")
                        .HasColumnType("int");

                    b.Property<int>("Idjuridiccion")
                        .HasColumnType("int");

                    b.Property<string>("Lugar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Movil")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Consulta");
                });

            modelBuilder.Entity("WSInformatica.Models.Dependencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dependencia");
                });

            modelBuilder.Entity("WSInformatica.Models.Efectivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdDependencia")
                        .HasColumnType("int");

                    b.Property<int>("Legajo")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdDependencia");

                    b.ToTable("Efectivo");
                });

            modelBuilder.Entity("WSInformatica.Models.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Apellido2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Clase")
                        .HasColumnType("int");

                    b.Property<int>("ConsultaId")
                        .HasColumnType("int");

                    b.Property<int?>("Dni")
                        .HasColumnType("int");

                    b.Property<string>("Nombre1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Resultado")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaId");

                    b.ToTable("Persona");
                });

            modelBuilder.Entity("WSInformatica.Models.TipoAutomotor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoAutomotor");
                });

            modelBuilder.Entity("WSInformatica.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsAdmin")
                        .HasColumnType("bit");

                    b.Property<int?>("IdEfectivo")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdEfectivo")
                        .IsUnique()
                        .HasFilter("[IdEfectivo] IS NOT NULL");

                    b.ToTable("User");
                });

            modelBuilder.Entity("WSInformatica.Models.Arma", b =>
                {
                    b.HasOne("WSInformatica.Models.Consulta", null)
                        .WithMany("Armas")
                        .HasForeignKey("ConsultaId");
                });

            modelBuilder.Entity("WSInformatica.Models.Automotor", b =>
                {
                    b.HasOne("WSInformatica.Models.Consulta", null)
                        .WithMany("Automotors")
                        .HasForeignKey("ConsultaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WSInformatica.Models.Efectivo", b =>
                {
                    b.HasOne("WSInformatica.Models.Dependencia", "Dependencia")
                        .WithMany("Efectivo")
                        .HasForeignKey("IdDependencia");

                    b.Navigation("Dependencia");
                });

            modelBuilder.Entity("WSInformatica.Models.Persona", b =>
                {
                    b.HasOne("WSInformatica.Models.Consulta", null)
                        .WithMany("Personas")
                        .HasForeignKey("ConsultaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WSInformatica.Models.User", b =>
                {
                    b.HasOne("WSInformatica.Models.Efectivo", "Efectivo")
                        .WithOne("User")
                        .HasForeignKey("WSInformatica.Models.User", "IdEfectivo");

                    b.Navigation("Efectivo");
                });

            modelBuilder.Entity("WSInformatica.Models.Consulta", b =>
                {
                    b.Navigation("Armas");

                    b.Navigation("Automotors");

                    b.Navigation("Personas");
                });

            modelBuilder.Entity("WSInformatica.Models.Dependencia", b =>
                {
                    b.Navigation("Efectivo");
                });

            modelBuilder.Entity("WSInformatica.Models.Efectivo", b =>
                {
                    b.Navigation("User")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
