USE [Informatica]
GO

/****** Object:  Table [dbo].[tipositemConsulta]    Script Date: 10/7/2023 07:53:14 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[tipositemConsulta](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[tipo] [nchar](105) NOT NULL,
 CONSTRAINT [PK_tipositemConsulta] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


